### ISSUE TITLE
Move scripts from dev/ into ivadomed package

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivadomed#285]
Some scripts are useful and if they stay in dev, they won't be used as much as they should. Issue triggered by https://github.com/neuropoly/ivado-medical-imaging/pull/282#issuecomment-641903615.

We are talking about these scripts:
- dev/compare_models.py: stat tests on models performance
- dev/convert_to_onnx.py: pt --> onnx
- dev/automate_training.py: hyperparam model optim
- dev/remove_small_lesion (Related to https://github.com/neuropoly/ivado-medical-imaging/issues/190)

Question: how should we call the folder enclosing those scripts? My suggestion would be to call it "scripts/" (commonly done).

**Comment by charleygros** [comment]
`scripts/` sounds good to me
(You meant `scripts/` and not `ivadomed/scripts/`, right?)

**Comment by jcohenadad** [comment]
actually i meant `ivadomed/scripts`. Being within the package will make the imports easier and will allow their inclusions in the unit tests. But maybe @Drulex has some opinion on this?

**Comment by Drulex** [comment]
> actually i meant `ivadomed/scripts`. Being within the package will make the imports easier and will allow their inclusions in the unit tests. But maybe @Drulex has some opinion on this?

I don't see any problem with `ivadomed/scripts`
