### ISSUE TITLE
Convert doc to full rst 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivadomed#286]
currently it is a hybrid between md and rst, which introduces complexity. Even thought md is more user-friendly, some features are not available, thus motivating the full-rst.

context: https://github.com/neuropoly/ivado-medical-imaging/issues/280#issuecomment-641337357

**Comment by Drulex** [comment]
I could do this, been meaning to learn `rst` for some time. Better to do it soon before the doc evolves too much.

**Comment by jcohenadad** [comment]
additional motivation:
- link "Models" is broken (as well as link to other files), here: file:///Users/julien/code/ivado-medical-imaging/docs/build/html/configuration_file.html#architecture
